import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "UniPaper App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex items-center justify-center min-h-screen p-20">
        {children}
      </body>
    </html>
  );
}
